# Generated by Django 4.1 on 2023-07-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_blog_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='myapp.blog'),
        ),
    ]
