# Generated by Django 4.1 on 2023-07-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_counts_alter_entry_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='counts',
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.blog'),
        ),
    ]
